INSERT INTO TIPO_CAMBIO (NOMBRE,ABREVIATURA,VALOR) VALUES ('SOL PERUANO','PEN', 1);
INSERT INTO TIPO_CAMBIO (NOMBRE,ABREVIATURA,VALOR) VALUES ('DÓLAR ESTADOUNIDENSE','USD', 0.2598);
INSERT INTO TIPO_CAMBIO (NOMBRE,ABREVIATURA,VALOR) VALUES ('EURO','EUR', 0.2434);
INSERT INTO TIPO_CAMBIO (NOMBRE,ABREVIATURA,VALOR) VALUES ('PESO MEXICANO','MXN', 4.7796);
INSERT INTO TIPO_CAMBIO (NOMBRE,ABREVIATURA,VALOR) VALUES ('YEN JAPONÉS','JPY', 34.9235);
INSERT INTO TIPO_CAMBIO (NOMBRE,ABREVIATURA,VALOR) VALUES ('YUAN CHINO','CNY', 1.7854);
INSERT INTO TIPO_CAMBIO (NOMBRE,ABREVIATURA,VALOR) VALUES ('RUBLO RUSO','RUB', 19.4652);
